//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeasingKustomization) DeepCopyInto(out *CeasingKustomization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeasingKustomization.
func (in *CeasingKustomization) DeepCopy() *CeasingKustomization {
	if in == nil {
		return nil
	}
	out := new(CeasingKustomization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CeasingKustomization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeasingKustomizationList) DeepCopyInto(out *CeasingKustomizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CeasingKustomization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeasingKustomizationList.
func (in *CeasingKustomizationList) DeepCopy() *CeasingKustomizationList {
	if in == nil {
		return nil
	}
	out := new(CeasingKustomizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CeasingKustomizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeasingKustomizationSpec) DeepCopyInto(out *CeasingKustomizationSpec) {
	*out = *in
	out.TTL = in.TTL
	in.KustomizationTemplate.DeepCopyInto(&out.KustomizationTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeasingKustomizationSpec.
func (in *CeasingKustomizationSpec) DeepCopy() *CeasingKustomizationSpec {
	if in == nil {
		return nil
	}
	out := new(CeasingKustomizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CeasingKustomizationStatus) DeepCopyInto(out *CeasingKustomizationStatus) {
	*out = *in
	if in.LastReconciliationRunTime != nil {
		in, out := &in.LastReconciliationRunTime, &out.LastReconciliationRunTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CeasingKustomizationStatus.
func (in *CeasingKustomizationStatus) DeepCopy() *CeasingKustomizationStatus {
	if in == nil {
		return nil
	}
	out := new(CeasingKustomizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizationTemplate) DeepCopyInto(out *KustomizationTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizationTemplate.
func (in *KustomizationTemplate) DeepCopy() *KustomizationTemplate {
	if in == nil {
		return nil
	}
	out := new(KustomizationTemplate)
	in.DeepCopyInto(out)
	return out
}
