
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kustomize.raffis.github.io
  resources:
  - CeasingKustomizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kustomize.raffis.github.io
  resources:
  - CeasingKustomizations/status
  verbs:
  - get
  - patch
  - update
